@Backend_HostAddress = http://localhost:5057

### Get all the monetary_flows for a user
GET {{Backend_HostAddress}}/monetary_flow?page=1
Authorization: Bearer {{$auth.token()}}


### Add to monetary_flows for user
POST {{Backend_HostAddress}}/monetary_flow/add
Authorization: Bearer {{$auth.token()}}
Content-Type: application/json

{
  "GoalId": 1,
  "CategoryId": 1,
  "MonetaryValue": 120.27
}

### Delete to monetary_flows for user
DELETE {{Backend_HostAddress}}/monetary_flow/delete/6
Authorization: Bearer {{$auth.token()}}
Content-Type: application/json
