@Backend_HostAddress = https://api.karle.co.za/

### get all cash flows for business
GET {{Backend_HostAddress}}/monetary_flow?page=3



### REPONSE
#{
#  "success": true,
#  "data": [
#    {
#      "flowId": 20,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:21:07.55394"
#    },
#    {
#      "flowId": 19,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:21:07.043599"
#    },
#    {
#      "flowId": 18,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:21:06.482324"
#    },
#    {
#      "flowId": 17,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:21:05.906522"
#    },
#    {
#      "flowId": 16,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:21:05.345794"
#    },
#    {
#      "flowId": 15,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:21:04.830118"
#    },
#    {
#      "flowId": 14,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:21:04.199692"
#    },
#    {
#      "flowId": 13,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:21:03.50258"
#    },
#    {
#      "flowId": 12,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:20:50.799429"
#    },
#    {
#      "flowId": 11,
#      "goalName": "Washing machine",
#      "categoryName": "Test",
#      "monetaryValue": 120.27,
#      "createdDatetime": "2024-06-01T18:20:49.064826"
#    }
#  ]
#}

### add cash flow to business
POST {{Backend_HostAddress}}/monetary_flow/add
Content-Type: application/json

{
  "GoalId": 1,
  "CategoryId": 1,
  "MonetaryValue": 120.27
}

### REPONSE
#{
#  "success": true,
#  "data": 21
#}

### delete cashflow from business
DELETE {{Backend_HostAddress}}/monetary_flow/delete/6

### REPONSE
#{
#  "success": true,
#  "data": 6
#}

### get all categories
GET {{Backend_HostAddress}}/category

### REPONSE
#{
#  "success": true,
#  "data": [
#    {
#      "id": 1,
#      "name": "Test"
#    },
#    {
#      "id": 2,
#      "name": "Data"
#    }
#  ]
#}

###get all goals for a business

GET {{Backend_HostAddress}}/goal

### REPONSE
#{
#  "success": true,
#  "data": [
#    {
#      "id": 1,
#      "name": "Washing machine",
#      "description": "Heart",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-28T13:50:57.803402"
#    },
#    {
#      "id": 2,
#      "name": "Washing machine",
#      "description": "Heart",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-28T13:52:28.682247"
#    },
#    {
#      "id": 3,
#      "name": "Washing machine",
#      "description": "Heart",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-29T12:52:03.098652"
#    },
#    {
#      "id": 4,
#      "name": "Washing machine",
#      "description": "Heart",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-29T12:52:04.845295"
#    },
#    {
#      "id": 5,
#      "name": "1",
#      "description": "2",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-29T13:19:48.819193"
#    },
#    {
#      "id": 6,
#      "name": "1",
#      "description": "2",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-29T13:19:49.564853"
#    },
#    {
#      "id": 7,
#      "name": "1",
#      "description": "2",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-29T13:19:50.378267"
#    },
#    {
#      "id": 8,
#      "name": "1",
#      "description": "2",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-29T13:19:51.111769"
#    },
#    {
#      "id": 9,
#      "name": "1",
#      "description": "2",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-29T13:19:51.536515"
#    },
#    {
#      "id": 10,
#      "name": "1",
#      "description": "2",
#      "goalMonetaryValue": 12.00,
#      "goalDueDatetime": "2024-05-28T15:33:03",
#      "createdDatetime": "2024-05-29T13:19:53.349554"
#    }
#  ]
#}