@Backend_HostAddress = http://localhost:5057












### Get all monetry flows
GET {{Backend_HostAddress}}/monetary_flow

















GET {{Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

PUT {{Backend_HostAddress}}/goal/add
Content-Type: application/json

{
  "Name": "1",
  "Description": "2",
  "GoalMonetaryValue": 12,
  "GoalDueDatetime": "2024-05-28 Tue 15:33:03"
}

###

GET {{Backend_HostAddress}}/business
Content-Type: application/json

{
}

### GET One goal
GET {{Backend_HostAddress}}/goal/132132121

### GET 10 goals
GET {{Backend_HostAddress}}/goal

### GET 10 goals page 2

GET {{Backend_HostAddress}}/business/test/1




### DELETE mone flow
PATCH {{Backend_HostAddress}}/monetary_flow/delete
Content-Type: application/json

{
  "id": 1
}




###
GET {{Backend_HostAddress}}/monetary_flow/test/12
Content-Type:application/json

{
}


### PUT monetry flows
PUT {{Backend_HostAddress}}/monetary_flow/add
Content-Type: application/json

{
  "GoalId": 1,
  "CategoryId": 1,
  "MonetaryValue": 12.20
}
