name: Release

on:
  workflow_call: 
  workflow_dispatch:

permissions:
  contents: write
  security-events: write
  id-token: write

jobs:
  frontend-deploy:
    name: Frontend Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
        aws-region: "eu-west-1"
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Upload new Frontend Files
      run: |
        aws s3 rm --recursive s3://978251882572-wordle
        aws s3 cp ./frontend s3://978251882572-wordle --recursive

        
  backend-deploy:
    name: Backend Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
        aws-region: "eu-west-1"
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Create ZIP Package
      working-directory: ./server
      run: |
        zip -r deploy_package.zip .

    - name: Upload Package
      working-directory: ./server
      run: aws s3 cp deploy_package.zip s3://978251882572-deploy-bucket

    - name: Create New API Version
      run: aws elasticbeanstalk create-application-version --application-name api-app --source-bundle S3Bucket="978251882572-deploy-bucket",S3Key="deploy_package.zip" --version-label "deploy-${{ github.sha }}" --description "commit-sha-${{ github.sha }}"

    - name: Deploy API
      run: aws elasticbeanstalk update-environment --environment-name api-env --version-label "deploy-${{ github.sha }}"
